name: Model Training and Reporting

on: [push]

jobs:
  train-and-report:
    runs-on: ubuntu-latest
    permissions:
      contents: write # To checkout the repo and post commit comments
      issues: write # To post comments on issues
      pull-requests: write # To post comments on pull requests
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Needed to checkout all branches

      - name: 'Set up Python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 'Install dependencies'
        run: pip install -r requirements.txt # Create a requirements.txt file

      - name: 'Configure DVC with GCS'
        env:
          GCP_CREDS: ${{ secrets.GCP_SA_KEY }} # Store your service account key as a secret
        run: |
          echo "$GCP_CREDS" > gcloud-creds.json
          # gcloud auth activate-service-account --key-file=gcloud-creds.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcloud-creds.json" >> $GITHUB_ENV
          dvc remote modify gcsb projectname thermal-effort-461417-i4
      - name: 'Train on all branches'
        run: |
          for branch in $(git branch -r | grep -v HEAD); do
            git checkout ${branch#origin/}
            dvc pull
            python train.py
            echo "## Accuracy for ${branch#origin/}" >> report.md
            cat results/metrics.json | jq -r '.accuracy' >> report.md
          done
      - name: 'Setup CML'
        uses: iterative/setup-cml@v2
      - name: 'Create CML report'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml comment create report.md
